### ISSUE TITLE
Lacking a default config/sync directory

### ISSUE THREAD

**Issue by pjcdawkins** [platformsh/template-drupal8#14]
Needs the directory:
https://github.com/platformsh/platformsh-example-drupal8/tree/master/config/sync

and the config:
https://github.com/platformsh/platformsh-example-drupal8/blob/master/web/sites/default/settings.php#L33

**Comment by Crell** [comment]
Huh.  I thought that was provided by the upstream drupal composer project, but apparently not.  I'll add a .gitkeep file to the builder.
